In [30]:
import numpy as np

In [31]:
#sample math
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [32]:
b = np.array([[10,20,30],[40,50,50]])
b

array([[10, 20, 30],
       [40, 50, 50]])

In [33]:
#create array via assignment
np.random.seed(25)
c = 36*np.random.rand(6)
c

array([31.32446892, 20.96196943, 10.03820187,  6.69280436, 14.79960461,
        4.2255197 ])

In [34]:
d = np.arange(1,35)
d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

In [35]:
# Sample arthimeic
a*10

array([10, 20, 30, 40, 50, 60])

In [36]:
c + a

array([32.32446892, 22.96196943, 13.03820187, 10.69280436, 19.79960461,
       10.2255197 ])

In [37]:
c-a

array([30.32446892, 18.96196943,  7.03820187,  2.69280436,  9.79960461,
       -1.7744803 ])

In [38]:
c*a

array([31.32446892, 41.92393886, 30.1146056 , 26.77121742, 73.99802303,
       25.35311818])

In [39]:
c/a

array([31.32446892, 10.48098472,  3.34606729,  1.67320109,  2.95992092,
        0.70425328])

In [41]:
# multiplying matrices and basic linear algebra
aa = np.array([[2.,4.,6.,],[1.,3.,5.],[10.,20.,30.]])
aa

array([[ 2.,  4.,  6.],
       [ 1.,  3.,  5.],
       [10., 20., 30.]])

In [42]:
bb = np.array([[0.,1.,2.,],[3.,4.,5.],[6.,7.,8.]])
bb

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [43]:
aa*bb

array([[  0.,   4.,  12.],
       [  3.,  12.,  25.],
       [ 60., 140., 240.]])

In [44]:
#.dot product
# here we multiply rows * columns , first row for all colunms, second row for all columns and so on.
np.dot(aa,bb)

array([[ 48.,  60.,  72.],
       [ 39.,  48.,  57.],
       [240., 300., 360.]])